# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Union
from typing_extensions import TypeAlias

from .price_edited_webhook_event import PriceEditedWebhookEvent
from .invoice_edited_webhook_event import InvoiceEditedWebhookEvent
from .invoice_issued_webhook_event import InvoiceIssuedWebhookEvent
from .customer_edited_webhook_event import CustomerEditedWebhookEvent
from .customer_created_webhook_event import CustomerCreatedWebhookEvent
from .backfill_reverted_webhook_event import BackfillRevertedWebhookEvent
from .backfill_reflected_webhook_event import BackfillReflectedWebhookEvent
from .credit_note_issued_webhook_event import CreditNoteIssuedWebhookEvent
from .subscription_ended_webhook_event import SubscriptionEndedWebhookEvent
from .invoice_sync_failed_webhook_event import InvoiceSyncFailedWebhookEvent
from .resource_event_test_webhook_event import ResourceEventTestWebhookEvent
from .subscription_edited_webhook_event import SubscriptionEditedWebhookEvent
from .invoice_issue_failed_webhook_event import InvoiceIssueFailedWebhookEvent
from .plan_version_created_webhook_event import PlanVersionCreatedWebhookEvent
from .subscription_created_webhook_event import SubscriptionCreatedWebhookEvent
from .subscription_started_webhook_event import SubscriptionStartedWebhookEvent
from .event_unmatched_event_webhook_event import EventUnmatchedEventWebhookEvent
from .billable_metric_edited_webhook_event import BillableMetricEditedWebhookEvent
from .invoice_issued_summary_webhook_event import InvoiceIssuedSummaryWebhookEvent
from .invoice_payment_failed_webhook_event import InvoicePaymentFailedWebhookEvent
from .invoice_sync_succeeded_webhook_event import InvoiceSyncSucceededWebhookEvent
from .payment_method_created_webhook_event import PaymentMethodCreatedWebhookEvent
from .payment_method_deleted_webhook_event import PaymentMethodDeletedWebhookEvent
from .plan_default_version_set_webhook_event import PlanDefaultVersionSetWebhookEvent
from .subscription_trial_ended_webhook_event import SubscriptionTrialEndedWebhookEvent
from .invoice_payment_succeeded_webhook_event import InvoicePaymentSucceededWebhookEvent
from .invoice_undo_mark_as_paid_webhook_event import InvoiceUndoMarkAsPaidWebhookEvent
from .subscription_plan_changed_webhook_event import SubscriptionPlanChangedWebhookEvent
from .credit_note_marked_as_void_webhook_event import CreditNoteMarkedAsVoidWebhookEvent
from .invoice_cost_data_exported_webhook_event import InvoiceCostDataExportedWebhookEvent
from .invoice_payment_processing_webhook_event import InvoicePaymentProcessingWebhookEvent
from .subscription_cost_exceeded_webhook_event import SubscriptionCostExceededWebhookEvent
from .data_exports_transfer_error_webhook_event import DataExportsTransferErrorWebhookEvent
from .subscription_alert_disabled_webhook_event import SubscriptionAlertDisabledWebhookEvent
from .subscription_spend_exceeded_webhook_event import SubscriptionSpendExceededWebhookEvent
from .subscription_usage_exceeded_webhook_event import SubscriptionUsageExceededWebhookEvent
from .invoice_invoice_date_elapsed_webhook_event import InvoiceInvoiceDateElapsedWebhookEvent
from .data_exports_transfer_success_webhook_event import DataExportsTransferSuccessWebhookEvent
from .invoice_accounting_sync_failed_webhook_event import InvoiceAccountingSyncFailedWebhookEvent
from .invoice_dunning_schedule_ended_webhook_event import InvoiceDunningScheduleEndedWebhookEvent
from .invoice_dunning_schedule_reset_webhook_event import InvoiceDunningScheduleResetWebhookEvent
from .customer_accounting_sync_failed_webhook_event import CustomerAccountingSyncFailedWebhookEvent
from .customer_credit_balance_dropped_webhook_event import CustomerCreditBalanceDroppedWebhookEvent
from .invoice_manually_marked_as_paid_webhook_event import InvoiceManuallyMarkedAsPaidWebhookEvent
from .invoice_manually_marked_as_void_webhook_event import InvoiceManuallyMarkedAsVoidWebhookEvent
from .customer_credit_balance_depleted_webhook_event import CustomerCreditBalanceDepletedWebhookEvent
from .ingestion_unmatched_customer_ids_webhook_event import IngestionUnmatchedCustomerIDsWebhookEvent
from .invoice_dunning_schedule_created_webhook_event import InvoiceDunningScheduleCreatedWebhookEvent
from .customer_credit_balance_recovered_webhook_event import CustomerCreditBalanceRecoveredWebhookEvent
from .invoice_accounting_sync_succeeded_webhook_event import InvoiceAccountingSyncSucceededWebhookEvent
from .subscription_plan_version_changed_webhook_event import SubscriptionPlanVersionChangedWebhookEvent
from .credit_note_accounting_sync_failed_webhook_event import CreditNoteAccountingSyncFailedWebhookEvent
from .customer_accounting_sync_succeeded_webhook_event import CustomerAccountingSyncSucceededWebhookEvent
from .customer_credit_ledger_incremented_webhook_event import CustomerCreditLedgerIncrementedWebhookEvent
from .metric_events_dropped_by_watermark_webhook_event import MetricEventsDroppedByWatermarkWebhookEvent
from .sales_order_accounting_sync_failed_webhook_event import SalesOrderAccountingSyncFailedWebhookEvent
from .subscription_grouped_cost_exceeded_webhook_event import SubscriptionGroupedCostExceededWebhookEvent
from .subscription_plan_change_scheduled_webhook_event import SubscriptionPlanChangeScheduledWebhookEvent
from .transaction_accounting_sync_failed_webhook_event import TransactionAccountingSyncFailedWebhookEvent
from .credit_block_accounting_sync_failed_webhook_event import CreditBlockAccountingSyncFailedWebhookEvent
from .subscription_accounting_sync_failed_webhook_event import SubscriptionAccountingSyncFailedWebhookEvent
from .subscription_cancellation_scheduled_webhook_event import SubscriptionCancellationScheduledWebhookEvent
from .customer_balance_transaction_created_webhook_event import CustomerBalanceTransactionCreatedWebhookEvent
from .credit_note_accounting_sync_succeeded_webhook_event import CreditNoteAccountingSyncSucceededWebhookEvent
from .sales_order_accounting_sync_succeeded_webhook_event import SalesOrderAccountingSyncSucceededWebhookEvent
from .subscription_cancellation_unscheduled_webhook_event import SubscriptionCancellationUnscheduledWebhookEvent
from .subscription_license_allocation_reset_webhook_event import SubscriptionLicenseAllocationResetWebhookEvent
from .transaction_accounting_sync_succeeded_webhook_event import TransactionAccountingSyncSucceededWebhookEvent
from .credit_block_accounting_sync_succeeded_webhook_event import CreditBlockAccountingSyncSucceededWebhookEvent
from .invoice_due_date_recalculation_started_webhook_event import InvoiceDueDateRecalculationStartedWebhookEvent
from .invoice_dunning_schedule_step_executed_webhook_event import InvoiceDunningScheduleStepExecutedWebhookEvent
from .subscription_accounting_sync_succeeded_webhook_event import SubscriptionAccountingSyncSucceededWebhookEvent
from .invoice_due_date_recalculation_canceled_webhook_event import InvoiceDueDateRecalculationCanceledWebhookEvent
from .subscription_fixed_fee_quantity_updated_webhook_event import SubscriptionFixedFeeQuantityUpdatedWebhookEvent
from .invoice_due_date_recalculation_completed_webhook_event import InvoiceDueDateRecalculationCompletedWebhookEvent
from .invoice_automation_schedule_step_executed_webhook_event import InvoiceAutomationScheduleStepExecutedWebhookEvent
from .subscription_invoicing_threshold_exceeded_webhook_event import SubscriptionInvoicingThresholdExceededWebhookEvent
from .subscription_plan_version_change_scheduled_webhook_event import SubscriptionPlanVersionChangeScheduledWebhookEvent
from .subscription_license_balance_threshold_reached_webhook_event import (
    SubscriptionLicenseBalanceThresholdReachedWebhookEvent,
)

__all__ = ["UnwrapWebhookEvent"]

UnwrapWebhookEvent: TypeAlias = Union[
    BackfillReflectedWebhookEvent,
    BackfillRevertedWebhookEvent,
    BillableMetricEditedWebhookEvent,
    CreditBlockAccountingSyncFailedWebhookEvent,
    CreditBlockAccountingSyncSucceededWebhookEvent,
    CreditNoteAccountingSyncFailedWebhookEvent,
    CreditNoteAccountingSyncSucceededWebhookEvent,
    CreditNoteIssuedWebhookEvent,
    CreditNoteMarkedAsVoidWebhookEvent,
    CustomerAccountingSyncFailedWebhookEvent,
    CustomerAccountingSyncSucceededWebhookEvent,
    CustomerBalanceTransactionCreatedWebhookEvent,
    CustomerCreatedWebhookEvent,
    CustomerCreditBalanceDepletedWebhookEvent,
    CustomerCreditBalanceDroppedWebhookEvent,
    CustomerCreditBalanceRecoveredWebhookEvent,
    CustomerCreditLedgerIncrementedWebhookEvent,
    CustomerEditedWebhookEvent,
    DataExportsTransferErrorWebhookEvent,
    DataExportsTransferSuccessWebhookEvent,
    EventUnmatchedEventWebhookEvent,
    IngestionUnmatchedCustomerIDsWebhookEvent,
    InvoiceAccountingSyncFailedWebhookEvent,
    InvoiceAccountingSyncSucceededWebhookEvent,
    InvoiceAutomationScheduleStepExecutedWebhookEvent,
    InvoiceCostDataExportedWebhookEvent,
    InvoiceDunningScheduleCreatedWebhookEvent,
    InvoiceDunningScheduleEndedWebhookEvent,
    InvoiceDunningScheduleResetWebhookEvent,
    InvoiceDunningScheduleStepExecutedWebhookEvent,
    InvoiceEditedWebhookEvent,
    InvoiceInvoiceDateElapsedWebhookEvent,
    InvoiceIssueFailedWebhookEvent,
    InvoiceIssuedWebhookEvent,
    InvoiceIssuedSummaryWebhookEvent,
    InvoiceManuallyMarkedAsPaidWebhookEvent,
    InvoiceManuallyMarkedAsVoidWebhookEvent,
    InvoicePaymentFailedWebhookEvent,
    InvoicePaymentProcessingWebhookEvent,
    InvoicePaymentSucceededWebhookEvent,
    InvoiceSyncFailedWebhookEvent,
    InvoiceSyncSucceededWebhookEvent,
    InvoiceUndoMarkAsPaidWebhookEvent,
    InvoiceDueDateRecalculationCanceledWebhookEvent,
    InvoiceDueDateRecalculationCompletedWebhookEvent,
    InvoiceDueDateRecalculationStartedWebhookEvent,
    MetricEventsDroppedByWatermarkWebhookEvent,
    PaymentMethodCreatedWebhookEvent,
    PaymentMethodDeletedWebhookEvent,
    PlanDefaultVersionSetWebhookEvent,
    PlanVersionCreatedWebhookEvent,
    PriceEditedWebhookEvent,
    ResourceEventTestWebhookEvent,
    SalesOrderAccountingSyncFailedWebhookEvent,
    SalesOrderAccountingSyncSucceededWebhookEvent,
    SubscriptionAccountingSyncFailedWebhookEvent,
    SubscriptionAccountingSyncSucceededWebhookEvent,
    SubscriptionAlertDisabledWebhookEvent,
    SubscriptionCancellationScheduledWebhookEvent,
    SubscriptionCancellationUnscheduledWebhookEvent,
    SubscriptionCostExceededWebhookEvent,
    SubscriptionCreatedWebhookEvent,
    SubscriptionEditedWebhookEvent,
    SubscriptionEndedWebhookEvent,
    SubscriptionFixedFeeQuantityUpdatedWebhookEvent,
    SubscriptionGroupedCostExceededWebhookEvent,
    SubscriptionInvoicingThresholdExceededWebhookEvent,
    SubscriptionLicenseAllocationResetWebhookEvent,
    SubscriptionLicenseBalanceThresholdReachedWebhookEvent,
    SubscriptionPlanChangeScheduledWebhookEvent,
    SubscriptionPlanChangedWebhookEvent,
    SubscriptionPlanVersionChangeScheduledWebhookEvent,
    SubscriptionPlanVersionChangedWebhookEvent,
    SubscriptionSpendExceededWebhookEvent,
    SubscriptionStartedWebhookEvent,
    SubscriptionTrialEndedWebhookEvent,
    SubscriptionUsageExceededWebhookEvent,
    TransactionAccountingSyncFailedWebhookEvent,
    TransactionAccountingSyncSucceededWebhookEvent,
]
